version: "3.7"

services:

  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: server
      APP_PORT: 5000
    depends_on:
     - server
    
  server:
    image: danieldedek/test2-image:1.0
    restart: unless-stopped
    user: "1000:1000"
    init: true
    volumes:
      - /home/umbrel/umbrel/home/uploads:/app/uploads
